### PR TITLE
Add support for Inkline 3

### LINKED ISSUE #1: Inkline 3 support ?
Hi ! It's been a while !

I wanted to test `vue-cli-plugin-inkline` and it installs `^2.0.0`(in both vue 2 and 3 fresh projects).

I may be able to work on a PR for that this week; all I need to know is if there is any known compatibility issue between Inkline 3 and Vue 2/3.

### PR DESCRIPTION
**Pull request by mtancoigne**
- [x] Update dependencies
- [x] Add support for Vue3 + Inkline3
- [x] Keep support for vue 2 with `--vue2` option (installs Inkline 2.x)
- [x] Update README
- [x] Replace old unmaintained tests by something else
- [x] Add Github actions

Closes #1

### CODE REVIEW

**Comment by mtancoigne** [comment]
@alexgrozav The tests seems broken, I didn't fix them.

During dev, to check if everything _runs fine_ I created 092e9b2, which is basically dummy apps and NPM scripts to install the plugin and build it. If you think that can replace the tests, i'll remove the `tests` dir and dig into Github actions to run the NPM scripts in the CI. Otherwise i'll drop the commit :)

**Comment by mtancoigne** [comment]
Also, I bumped the version to `3.0.0`; I think we have a breaking change here :)

**Comment by mtancoigne** [comment]
An attempt to integrate the dummy tests with Github actions gives a pretty good result: https://github.com/el-cms/vue-cli-plugin-inkline/actions/runs/1701594266

The action tests the three NPM scripts on Node 14 and 16.

**Comment by alexgrozav** [comment]
That's amazing! Thank you so much for the wonderful work, @mtancoigne!

**Comment by mtancoigne** [comment]
You're welcome!

**Pull request merged**
