### PR TITLE
Wip - Initial work

### PR DESCRIPTION
**Pull request by mtancoigne**

### CODE REVIEW

**Comment by mtancoigne** [comment]
Wait, what ? You merged this ? all the commits are in a WIP state :/ there is no logo, this is not even tested... Sorry if it was unclear :/

**Comment by alexgrozav** [comment]
It's alright, it's unreleased on npm, so we don't need to worry about anyone installing it. It'll be ready when it's ready. 

Until then, the work you did is a great starting point. 

I'll be back from my vacation next weekend and we can work on it further.

**Comment by mtancoigne** [comment]
Ok, don't worry, i'll try to continue on it this week.

**Comment by mtancoigne** [comment]
I finished the initial setup, and tried it locally. Don't you think we should force-push the changes to have a cleaner starting history ?

**Comment by alexgrozav** [comment]
I've added you as a collaborator with Write permission. Let's force push this! :)

**Pull request merged**
